# Generated by Django 4.2 on 2025-09-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagelog',
            name='recipient',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('received', 'Received')], max_length=10),
        ),
    ]
