# Generated by Django 4.2 on 2025-09-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagelog',
            name='direction',
            field=models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagelog',
            name='sender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
