# Generated by Django 4.2 on 2025-09-15 14:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dutyassignment',
            old_name='assignment_date',
            new_name='assigned_at',
        ),
        migrations.RemoveField(
            model_name='dutyassignment',
            name='guard',
        ),
        migrations.AddField(
            model_name='dutyassignment',
            name='guards',
            field=models.ManyToManyField(limit_choices_to={'role__in': ['police', 'security_guard', 'commando']}, related_name='duty_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
