# Generated by Django 4.2 on 2025-09-17 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guards', '0002_rename_assignment_date_dutyassignment_assigned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityguardprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='guard_photos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
    ]
